//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechNeurons.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int? Id { get; set; }

        [Required(ErrorMessage ="Name is required")]
        [StringLength(200, MinimumLength = 3, ErrorMessage = "Name minimum 3 character")]
        public string name { get; set; }
        [Required(ErrorMessage = "Age is required")]
        [Range(22,60,ErrorMessage ="Age between 22 to 60")]
        public Nullable<int> age { get; set; }
        [Required(ErrorMessage = "Experience is required")]
        public string experience { get; set; }
        [Required(ErrorMessage = "Department is required")]
        public string department { get; set; }
        [Required(ErrorMessage = "Gender is required")]
        public string gender { get; set; }
        [Required(ErrorMessage = "Address is required")]
        [StringLength(200,MinimumLength =20,ErrorMessage =" Enter Detail Address minimum 15 character")]
        public string address { get; set; }
    }
}
